labels:
  practica: k8s
  formacion: containers-kubernetes
  app: django

replicas: 1

imagen: localhost:5000/django

imagePullPolicy: Always

host: django.local

redis:
  fullnameOverride: mi-redis
  auth:
    enabled: false
  replica:
    replicaCount: 1
